### ISSUE TITLE
Copy-paste-os from Tinboard

### ISSUE THREAD

**Issue by TomJGooding** [davep/braindrop#4]
Hey Dave, nice to see you working with Textual again! Just thought you should know I spotted a couple of copy-paste-os from Tinboard in the README. Maybe elsewhere in the repo too, but GitHub hasn't indexing yet to do a search!

**Comment by davep** [comment]
Yeah, there's a good chance of that; thanks for flagging it up.

**Comment by davep** [comment]
Looks like it is just the README:

![Screenshot 2024-12-31 at 14 35 27](https://github.com/user-attachments/assets/8b90b81e-c49d-4559-95cd-6e89b58c7a28)
